using static System.Console;
int a, b, c;
bool pergunta1, pergunta2, pergunta3, pergunta4;
Write("Digite o primeiro valor: ");
a = int.Parse(ReadLine());
Write("Digite o segundo valor: ");
b = int.Parse(ReadLine());
Write("Digite o terceiro valor: ");
c = int.Parse(ReadLine());
pergunta1 = (a == c);
pergunta2 = (b != a);
pergunta3 = (b > c);
pergunta4 = (a <= c);
Write($"O primero valor é igual ao terceiro valor: {pergunta1}");
Write($"O segundo valor é diferente do primeiro valor: {pergunta2}");
Write($"O segundo valor é maior que o terceiro valor: {pergunta3}");
Write($"O primero valor é menor ou igual ao terciro valor: {pergunta4}");
bool resultado1 = pergunta1 & pergunta3;
bool resultado2 = pergunta2 | pergunta4;
bool resultado3 = !pergunta1;
Write($"A primeira pergunta e a terceira pergunta são verdadeiras: {resultado1}");
Write($"A segunda pergunta e a quarta pergunta são verdadeiras: {resultado2}");
Write($"A negação da primeira pergunta é verdadeira: {resultado3}");
